### ISSUE TITLE
Windows 10+VSCode: Markdown Oxide client: couldn't create connection to server.

### ISSUE THREAD

**Issue by plule** [Feel-ix-343/markdown-oxide#73]
After installing the markdown-oxide extension on VSCode, it fails to start the language server:

```
[Error - 10:41:30 AM] Markdown Oxide client: couldn't create connection to server.
Error: Unsupported server configuration {
    "command": null
}
    at c:\Users\user\.vscode\extensions\felixzeller.markdown-oxide-1.0.4\client\node_modules\vscode-languageclient\lib\node\main.js:466:35
    at LanguageClient.createConnection (c:\Users\user\.vscode\extensions\felixzeller.markdown-oxide-1.0.4\client\node_modules\vscode-languageclient\lib\common\client.js:1144:28)
    at LanguageClient.start (c:\Users\user\.vscode\extensions\felixzeller.markdown-oxide-1.0.4\client\node_modules\vscode-languageclient\lib\common\client.js:681:32)
```

Building markdown-oxide and setting it in the path solves the problem

**Comment by Feel-ix-343** [comment]
Thank you! We will get this sorted out

**Comment by gmccullo** [comment]
Ditto. 

```
[Error - 7:33:30 AM] Markdown Oxide client: couldn't create connection to server.
Error: Unsupported server configuration {
    "command": null
}
	at c:\Users\gary\.vscode\extensions\felixzeller.markdown-oxide-1.0.4\client\node_modules\vscode-languageclient\lib\node\main.js:466:35
	at async LanguageClient.createConnection (c:\Users\gary\.vscode\extensions\felixzeller.markdown-oxide-1.0.4\client\node_modules\vscode-languageclient\lib\common\client.js:1144:28)
	at async LanguageClient.start (c:\Users\gary\.vscode\extensions\felixzeller.markdown-oxide-1.0.4\client\node_modules\vscode-languageclient\lib\common\client.js:681:32)
```

**Comment by Feel-ix-343** [comment]
As of the most recent version on marketplace v1.0.5, this might be fixed. 

I don't have Windows right now, so I cannot test it yet. 

I will set up a virtual machine to test it another time, but if you see this and find that it is working, let me know. 

Thank you!

**Comment by Feel-ix-343** [comment]
(if i forget to do this in v1, please reopen)
